# Based on FE10
#https://fireemblem.fandom.com/wiki/List_of_classes_in_Fire_Emblem:_Radiant_Dawn
class Unit():
    def __init__ Unit(self):
        self.pos = None
        self.hasMoved = False

    def statLoad(self, data):
        self.name = data[0]
        self.clss = data[1]
        self.lv = data[2]
        self.hp = [data[3], data[3]]
        self.str = data[4]
        self.mag = data[5]
        self.skl = data[6]
        self.spd = data[7]
        self.lck = data[8]
        self.df = data[9]
        self.res = data[10]
        self.con = data[11]
        self.wt = data[12]
        self.mov = data[13]
    
    def classStats(self):
        d = dict()
        d['hero'] = ([['sword'], ['S']], set(['shove']))
        d['vanguard'] = ([['sword', 'axe'], ['SS', 'SS']], set('shove', 'aether'))
        d['myrmidon'] = ([['sword'], ['D']], set('shove', 'crit+5'))
        d['swordmaster'] =  ([['sword'], ['S']], set(['shove', 'crit+10']))
        d['trueblade'] = ([['sword'], ['SS']], set(['shove', 'crit+20', 'astra']))
        d['soldier'] = ([['lance'], ['A']], set('shove'))
        d['halberdier'] = ([['lance'], ['S']], set('shove', 'crit+10', 'astra'))
        d['sentinel'] = ([['lance'], ['SS']], set('shove', 'crit+10', 'impale'))
        d['fighter'] = ([['axe'], ['A']], set('shove'))
        d['warrior'] = ([['axe'], ['S']], set('shove'))
        d['reaver'] = ([['axe', 'crossbow'], ['SS', 'A']], set('shove', 'crit+5', 'colossus'))
        d['archer'] = ([['bow'], ['A']], set('shove'))
        d['sniper'] = ([['bow', 'crossbow'], ['SS', 'A']], set('shove', 'crit+10'))
        d['marksman'] = ([['bow', 'crossbow'], ['SS', 'A']], set('shove', 'crit+15', 'deadeye', 'range+1'))
        d['armor lance'] = ([['lance'],[]])
        d['armor axe'] = 
        d['armor sword'] = 
        d['lance general'] = 
        d['axe general'] = 
        d['sword general'] = 
        d['marshall'] =
        d['black knight'] = 
        d['thief'] = 
        d['rogue'] = 
        d['whisper'] = 
        d['assassin'] = 
        d['bandit'] =
        d['fire mage'] = 
        d['thunder mage'] =
        d['wind mage'] = 
        d['light mage'] = 
        d['fire sage'] = 
        d['thunder sage'] = 
        d['wind sage'] = 
        d['light sage'] = 
        d['dark sage'] = 
        d['archsage anima'] = 
        d['archsage dark'] = 
        d['light priestess'] = 
        d['empress'] = 
        d['chancellor'] = 
        d['druid'] = 
        d['summoner'] =
        d['priest'] = 
        d['bishop'] = 
        d['saint'] = 
        d['cleric'] = 
        d['valkyrie'] = 
        d['sword knight'] = 
        d['lance knight'] = 
        d['axe knight'] = 
        d['bow knight'] = 
        d['blade paladin'] = 
        d['lance paladin'] = 
        d['axe paladin'] = 
        d['bow paladin'] = 
        d['gold knight'] = 
        d['silver knight'] = 
        d['pegasus knight'] = 
        d['falcon knight'] = 
        d['seraph knight'] = 
        d['queen'] = 
        d['dracoknight'] = 
        d['dragonmaster'] = 
        d['dragonlord'] = 
        d['lion'] = 
        d['lion king'] = 
        d['tiger'] = 
        d['cat'] = 
        d['wolf'] = 
        d['wolf queen'] = 
        d['hawk'] = 
        d['hawk king'] = 
        d['raven'] = 
        d['raven king'] = 
        d['heron rafiel'] = 
        d['heron leanne'] = 
        d['red dragon'] = 
        d['white dragon'] = 
        d['dragon king'] = 
        d['fire spirit'] = 
        d['thunder spirit'] = 
        d['wind spirit'] = 
        d['order incarnate'] = 
